config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  root to: 'posts#index'
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search', 'seek'
    end
  end

  resources :users, only: :show do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
    get :favorites, on: :member
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true, length: {maximum: 600}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :move_to_index, only: :destroy

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = @post.id
    if @comment.save
      render :post_comments
    else
      render :'posts/show'
    end
  end

  def destroy
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    @post = Post.find(params[:post_id])
    render :post_comments
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def move_to_index
    comment = Comment.find(params[:id])
    unless user_signed_in? && current_user.id == comment.user_id
      redirect_to root_path
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<% if user_signed_in? && post.user_id != current_user.id %>
  <%= form_with(model: [post, comment]) do |form| %>
    <%= form.text_area :text, placeholder: "コメントを入力してください", rows: "4", class: "comment-form" %><br>
    <%= form.submit "コメントを送る", class: "comment-btn" %>
  <% end %>
<% else %>
  <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
<% end %>

app/views/comments/_post_comments.html.erb
<% post.comments.each do |comment| %>
    <strong><%= link_to comment.user.nickname, user_path(comment.user_id) %>：</strong>
    <%= comment.text %>
  <% if user_signed_in? && comment.user_id == current_user.id %>
    <%= link_to "削除", post_comment_path(comment.post, comment), method: :delete, remote: true %>
  <% end %><br>
<% end %>

app/views/comments/post_comments.js.erb
$("#comments-area").html("<%= j(render 'comments/post_comments', post: @post, comment: @comment) %>");
$("textarea").val('');