config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  root to: 'posts#index'
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search', 'seek'
    end
  end

  resources :users, only: :show do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
    get :favorites, on: :member
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :following, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :following, source: :followed
  has_many :follower_user, through: :followed, source: :following
  has_many :favorites
  has_many :fav_posts, through: :favorites, source: :post
  has_one_attached :avatar_image

  def follow(user_id)
    following.create(followed_id: user_id)
  end

  def unfollow(user_id)
    following.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  validates :nickname, presence: true, length: { maximum: 20 }
  validates :password,
  format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字混合6文字以上で入力してください' }
  validates :profile, length: { maximum: 160 }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  protected

  def after_update_path_for(resource)
    user_path(current_user.id)
  end

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @following_users = @user.following_user
    @follower_users = @user.follower_user
    @posts = @user.posts.page(params[:page]).reverse_order.per(3)
    favorites = Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorite_list = Post.find(favorites)
  end

  def follows
    @users = @user.following_user.page(params[:page]).per(3).reverse_order
  end
  
  def followers
    @users = @user.follower_user.page(params[:page]).per(3).reverse_order
  end

  def favorites
    @fav_posts = @user.fav_posts.page(params[:page]).per(5).reverse_order
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<div class="follow-index">
  <div id="follow-count">
    <%= link_to follows_user_path(user) do %>
      <h6>フォロー<%= @following_users.count %></h6>
    <% end %>
  </div>
  <div id="follower-count">
    <%= link_to followers_user_path(user) do %>
      <h6>フォロワー<%= @follower_users.count %></h6>
    <% end %>
  </div>
</div>

<%= link_to 'フォロー', user_relationships_path(user.id), method: :post, remote: true, class:"btn-sm btn-success" %>

app/views/users/_follow_form.html.erb
  <div id="follow-form">
    <% if current_user.following?(user) %>
      <%= render 'unfollow', user: @user %>
    <% else %>
      <%= render 'follow', user: @user %>
    <% end %>
  </div>

app/views/users/_unfollow.html.erb
<div class="follow-index">
  <div id="follow-count">
    <%= link_to follows_user_path(user) do %>
      <h6>フォロー<%= @following_users.count %></h6>
    <% end %>
  </div>
  <div id="follower-count">
    <%= link_to followers_user_path(user) do %>
      <h6>フォロワー<%= @follower_users.count %></h6>
    <% end %>
  </div>
</div>

<%= link_to 'フォロー中', user_relationships_path(user.id), method: :delete, remote: true, class: "btn-sm btn-danger" %>

app/views/users/favorites.html.erb
<%= render 'shared/header' %>

<div class="favorite-index">
  <% @fav_posts.each do |post| %>
    <%= link_to post.title, post_path(post) %>
    <%= image_tag post.post_images[0], class: "post-img" %>
  <% end %>
  <%= paginate @fav_posts %>
</div>

app/views/users/followers.html.erb
<%= render 'shared/header' %>

<div class="follow-index-main">

  <div class="follow-index-box">
    <div class="follow-header">
      <p class='follow-header-index'><%= link_to "フォロー", follows_user_path(@user) %></p>
      <p class='follow-header-index'><strong><%= link_to "フォロワー", followers_user_path(@user) %></strong></p>
    </div>
    <% @users.each do |user| %>
      <div class="follow-info">
        <%= link_to image_tag(user.avatar_image, class: 'follow-avatar'), user_path(user) %>
        <div class="follow-text">
          <%= link_to user.nickname, user_path(user), class: 'follows-followers' %>
          <%= user.profile %>
        </div>
        <div><%= link_to 'フォロー', '#', class: 'index-follow-btn' %></div>
      </div>
    <% end %>
    <%= paginate @users %>
  </div>

  <%= render 'shared/side_bar' %>

</div>

<%= render 'shared/footer' %>

app/views/users/follows.html.erb
<%= render 'shared/header' %>

<div class="follow-index-main">

  <div class="follow-index-box">
    <div class="follow-header">
      <p class='follow-header-index'><strong><%= link_to "フォロー", follows_user_path(@user) %></strong></p>
      <p class='follow-header-index'><%= link_to "フォロワー", followers_user_path(@user) %></p>
    </div>
    <% @users.each do |user| %>
      <div class="follow-info">
        <%= link_to image_tag(user.avatar_image, class: 'follow-avatar'), user_path(user) %>
        <div class="follow-text">
          <%= link_to user.nickname, user_path(user), class: 'follows-followers' %>
          <%= user.profile %>
        </div>
        <div><%= link_to 'フォロー', '#', class: 'index-follow-btn' %></div>
      </div>
    <% end %>
    <%= paginate @users %>
  </div>

  <%= render 'shared/side_bar' %>

</div>

<%= render 'shared/footer' %>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="user-show-main">

  <%# ユーザー情報 %>
  <div class="user-show-info">
    <div class="user-info-box">
      <%= image_tag @user.avatar_image, class: "user-show-avatar" %>
      <div class="user-show-nickname">
        <%= link_to @user.nickname, user_path(@user) %>
      </div>
      <div class="user-show-profile">
        <%= @user.profile %>
      </div>

      <% unless user_signed_in? && current_user.id != @user.id %>
        <div class="follow-follower-count">
          <div id="follow-count">
            <%= link_to follows_user_path(@user), class: "follow-follower-number" do %>
              <p><span><%= @following_users.count %></span> フォロー</p>
            <% end %>
          </div>
          <div id="follower-count">
            <%= link_to followers_user_path(@user), class: "follow-follower-number" do %>
              <p><span><%= @follower_users.count %></span> フォロワー</p>
            <% end %>
          </div>
        </div>
      <% end %>
      
      <% if user_signed_in? %>
        <% if current_user.id == @user.id %>
          <p><%= link_to "プロフィールを編集する", edit_user_registration_path(@user.id) %></p>
        <% else %>
          <%= render 'follow_form', user: @user %>
        <% end %>
      <% end %>
    </div>

    <div class="user-info-category">
      フォロー中のカテゴリー
    </div>
  </div>
  <%# /ユーザー情報 %>

  <%# ユーザーに関連する投稿 %>
  <div class="user-show-posts">
    <div class="user-best-box">
      <%= @user.nickname %>さんのイチ推し！
    </div>

    <div class="user-all-posts">
      <div class="all-posts-header">
        <%= link_to "投稿一覧", "#" %>
        <%= link_to "いいね", favorites_user_path(@user) %>
        <%= @favorite_list.count %>
        <%= "コメントした投稿" %>
      </div>
      <% @posts.each do |post| %>
        <div class="user-each-posts">
          <%= link_to image_tag(post.post_images[0], class: "each-posts-img"), post_path(post) %>
          <div class="each-posts-info">
            <%= link_to image_tag(post.user.avatar_image, class: "each-posts-avatar"), user_path(@user) %>
            <%= link_to @user.nickname, user_path(@user) %><br>
            <%= post.created_at.strftime('%Y/%m/%d') %><br>
            <%= link_to post.title, post_path(post) %><br>
            <%= post.category.name %><br>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @posts %>

  </div>
  <%# /ユーザーに関連する投稿 %>

</div>

<%= render 'shared/footer' %>