config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  root to: 'posts#index'
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search', 'seek'
    end
  end

  resources :users, only: :show do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
    get :favorites, on: :member
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <p><small>&copy; 2022 Osintro</small></p>
</footer>

app/views/shared/_header.html.erb
<header class="top-page-header">
  <h1 class="logo"><a href="/">Osintro</a></h1>

  <div class="search-bar-contents">
    <%= search_form_for Post.ransack(params[:q]), url: seek_posts_path, html: {id: 'search-form'} do |f|%>
      <%= f.collection_select(:category_id_eq, Category.all, :id, :name, {include_blank: "---"}) %>
      <%= f.text_field :title_or_content, placeholder: 'キーワードを入力', value: params[:q]&.dig(:title_or_content), class: 'input-box' %>
      <%= f.label :submit, class: 'search-button' do %>
        <input type="submit" value="検索" class="send">
        <%= f.submit :submit, id: "q_submit", style: "display: none;" %>
      <% end %>
    <% end %>
  </div>

  <nav>
    <ul class="lists-right">
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "login-out" %></li>
      <% else %>
        <li><%= link_to "ログイン", new_user_session_path, class: "login-out" %></li>
        <li><%= link_to "新規登録", new_user_registration_path, class: "login-out" %></li>
      <% end %>
    </ul>
    <%= link_to "投稿する", new_post_path, class: "new-post-btn" %>
  </nav>

</header>

app/views/shared/_second_header.html.erb
<header class="second-header">
  <%= link_to "Osintro", root_path %>
</header>

app/views/shared/_side_bar.html.erb
<%# サイドバー %>
<aside>
  <h3 class="sub-title">カテゴリー</h3>
  <ul class="sub-menu">
    <li>本</li>
    <li>ミュージック・楽器</li>
    <li>動画・映像作品</li>
    <li>ゲーム</li>
    <li>家電・AV機器</li>
    <li>パソコン・周辺機器</li>
    <li>文房具・オフィス用品</li>
    <li>家具・インテリア</li>
    <li>ペット・動物</li>
    <li>食品・飲料・お酒</li>
    <li>日用品・化粧品</li>
    <li>ベビー・おもちゃ・ホビー</li>
    <li>ファッション</li>
    <li>スポーツ・アウトドア</li>
    <li>車・バイク</li>
    <li>その他</li>
  </ul>
</aside>
<%# /サイドバー %>