config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  root to: 'posts#index'
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search', 'seek'
    end
  end

  resources :users, only: :show do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
    get :favorites, on: :member
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations
  has_many_attached :post_images

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/post_form.rb
class PostForm
  include ActiveModel::Model

  attr_accessor(
    :post_images, :title, :content, :category_id, :link, :user_id, :id,
    :created_at, :datetime, :updated_at, :datetime, :tag_name
  )

  validates :post_images, length: { minimum: 1, maximum: 4, message: "は1枚〜4枚添付してください" }
  with_options presence: true do
    validates :title, length: {maximum: 40}
    validates :content, length: {maximum: 1000}
  end
  validates :category_id, numericality: { other_than: 0, message: "を選択してください" }

  def save
    post = Post.create(post_images: post_images, title: title, content: content, category_id: category_id, link: link, user_id: user_id)
    tag = Tag.where(tag_name: tag_name).first_or_initialize
    tag.save
    PostTagRelation.create(post_id: post.id, tag_id: tag.id)
  end

  def update(params, post)
    post.post_tag_relations.destroy_all
    tag_name = params.delete(:tag_name)
    tag = Tag.where(tag_name: tag_name).first_or_initialize if tag_name.present?
    tag.save if tag_name.present?
    post.update(params)
    PostTagRelation.create(post_id: post.id, tag_id: tag.id) if tag_name.present?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]

  def index
    @posts = Post.all.page(params[:page]).reverse_order.per(9)
  end

  def new
    @post_form = PostForm.new
  end

  def create
    @post_form = PostForm.new(post_form_params)
    if @post_form.valid?
      @post_form.save
      redirect_to root_path
    else
      render :new
    end 
  end

  def show
    @comment = Comment.new
  end

  def edit
    post_attributes = @post.attributes
    @post_form = PostForm.new(post_attributes)
    @post_form.tag_name = @post.tags&.first&.tag_name
  end

  def update
    @post_form = PostForm.new(post_form_params)
    @post_form.post_images ||= @post.post_images.blobs
    if @post_form.valid?
      @post_form.update(post_form_params, @post)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def search
    return nil if params[:keyword] == ""
    tag = Tag.where(['tag_name LIKE ?', "%#{params[:keyword]}%"])
    render json:{keyword: tag}
  end
  
  def seek
    if params[:q]&.dig(:title_or_content)
      squished_keywords = params[:q][:title_or_content].squish
      params[:q][:title_or_content_cont_any] = squished_keywords.split(/[[:blank:]]/)
    end
    @result = Post.ransack(params[:q]).result
  end

  private

  def post_form_params
    params.require(:post_form).permit(:tag_name, {post_images: []}, :title, :content, :category_id, :link).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= render "shared/second_header" %>

<div class="new-post-main">
  <%= form_with model: @post_form, url: url, method: method, id: "new-post", local: true do |f|%>
  <%= render 'shared/error_messages', model: f.object %>

  <div class="new-post-contents">

    <%# 投稿画像 %>
    <div class="img-upload-box">
      <div class="weight-bold-text">
        画像（4枚まで）
        <span class="indispensable">必須（1枚目はサムネイル画像になります）</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :post_images, name: 'post_form[post_images][]', data: {index: 0} %>
      </div>
      <div id="post-previews"></div>
    </div>
    <%# /投稿画像 %>

    <%# 投稿内容入力 %>
    <div class="new-post-box">
      <div class="post-form-box">
        <div class="post-form-text">
          タイトル
          <span class="indispensable">必須</span>
        </div>
        <div class="new-post-form">
          <%= f.text_area :title, class:"post-form-area", placeholder:"（40文字まで)", maxlength:"40" %>
        </div>
      </div>

      <div class="post-form-box">
        <div class="post-form-text">
          説明
          <span class="indispensable">必須</span>
        </div>
        <div class="new-post-form">
          <%= f.text_area :content, class:"post-form-area", id:"post-info", placeholder:"（1,000文字まで）",rows:"7" ,maxlength:"1000" %>
        </div>
      </div>

      <div class="post-form-box">
        <div class="post-form-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <div class="new-post-form">
          <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: "---"}, {class:"post-form-area", id:"item-category"}) %>
        </div>
      </div>

      <div class="post-form-box">
        <div class="post-form-text">
          リンク
        </div>
        <div class="new-post-form">
          <%= f.text_area :link, class:"post-form-area" %>
        </div>
      </div>

      <div class="post-form-box">
        <div class="post-form-text">
          タグ
        </div>
        <div class="new-post-form">
          <%= f.text_field :tag_name, class: "post-form-area" %>
          <div id="search-result"></div>
        </div>
      </div>
      <%# /投稿内容入力 %>
    </div>
  </div>

  <%# 投稿ボタン %>
  <div class="new-post-btn">
    <div><%= f.submit "推す！" ,class:"post-btn" %></div>
    <div><%=link_to 'キャンセル', root_path, class:"back-btn" %></div>
  </div>
  <%# /投稿ボタン %>

  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form', {url: post_path(@post.id), method: :patch} %>

app/views/posts/index.html.erb
<%= render "shared/header" %>

<div class="post-index">
  <!-- メインエリア -->
  <article>
    <div class="post-contents">
      <% @posts.each do |post| %>
        <ul>
          <li class="post-list">
            <%= link_to post_path(post.id),class: "post-card" do %>
              <%= image_tag post.post_images[0], class: "post-img" %>
              <h3 class="post-title"><%= post.title %></h3>
              <p class="post-info">投稿したユーザー<br><%= post.user.nickname %></p>
              <p class="post-info">カテゴリー<br><%= post.category.name %></p>
            <% end %>
          </li>
        </ul>
      <% end %>
      <%= paginate @posts %>
    </div>
  </article>

  <%= render 'shared/side_bar' %>

</div>

<%= render "shared/footer" %>

app/views/posts/new.html.erb
<%= render 'form', {url: posts_path, method: :post} %>

app/views/posts/seek.html.erb
<%= render 'shared/header' %>

<div class="seek-index-main">

  <% @result.each do |post| %>
    <%= post.title %>
  <% end %>

</div>

<%= render 'shared/side_bar' %>

<%= render 'shared/footer' %>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class="post-show-main">

  <div class="post-show-contents">

    <%# 投稿概要 %>
    <div class="post-show-box">
      <div class="post-show-header">
        <div class="post-show-info">
          投稿者 <%= image_tag @post.user.avatar_image, class: "avatar-thumbnail" %><%= link_to @post.user.nickname, user_path(@post.user_id) %><br>
          投稿日 <%= @post.created_at.strftime('%Y/%m/%d') %> 更新日 <%= @post.updated_at.strftime('%Y/%m/%d') %><br>
          <h2 class="post-show-title"><%= @post.title %></h2><br>
          <%= @post.category.name %>/<%= @post.tags&.first&.tag_name %>
        </div>
        <div id="favorite_btn_<%= @post.id %>">
          <%= render 'favorites/favorite', post: @post %>
        </div>
      </div>


      <div class="post-image-content">
        <%= image_tag @post.post_images[0], alt: "投稿画像", class: "show-main-img" %>
        <div class="show-other-images">
          <% @post.post_images[1..-1].each do |image| %>
            <div class="show-other-image">
              <%= image_tag image, class: "other-images" %>
            </div>
          <%end%>
        </div>
      </div>

      <div class="post-explain-box">
        <h2 class="post-explain-text">ここがイチ推し！</h2>
        <span><%= @post.content %></span>
      </div>

      <div class="link-cord">
        関連リンク：<%= text_url_to_link(h(@post.link)).html_safe %>
      </div>
    </div>
    <%# /投稿概要 %>

    <%# コメント %>
    <h3 class="comment-text">コメント一覧</h3>
    <div class="comment-box">
      <div id="comments-area">
        <%= render "comments/post_comments", post: @post %>
      </div>
      <div id="new-comment">
        <%= render "comments/form", post: @post, comment: @comment %>
      </div>
    </div>
    <%# /コメント %>

    <%# 編集・削除ボタン %>
    <div class="edit-delete">
      <% if user_signed_in? && @post.user_id == current_user.id %>
        <%= link_to "投稿の編集", edit_post_path(@post.id), method: :get, class: "post-edit-btn" %>
        <%= link_to "削除", post_path(@post.id), method: :delete, class:"post-destroy-btn" %>
      <% end %>
    </div>
    <%# /編集・削除ボタン %>
  </div>

  <%= render 'shared/side_bar' %>

</div>

<%= render "shared/footer" %>